### ISSUE TITLE
New image version is failing on setup stage

### ISSUE THREAD

**Issue by manuelbcd** [ThisIsQasim/TastyIgniter#3]
Hi @ThisIsQasim, firstly let me thank you for this docker file, you saved me a lot of time.

I was playing around with Tastyigniter using your images but just noticed that the last one is not allowing to accomplish the 1st setup page, it is probably related with a compatibility problem between PHP 7.1 and Tastyigniter (as far as I have invetigated it seems to be the PHP version but I'm not 100% sure).

`        "Created": "2020-05-17T22:44:42.274213301Z",
`

tested with an older image and it working like a charm ( "Created": "2020-04-27T21:07:03.695749804Z" )

Tested in two VMs both with Ubuntu 14.04

Regards

**Comment by ThisIsQasim** [comment]
Hey, I am glad I was of help.
Looks like I tested with an old cached image and pushed the broken image. Reverting back to 7.0. Thank you for reporting :)

**Comment by manuelbcd** [comment]
You are welcome Qasim.  Hope to bear a hand if I can

Best regards
