### ISSUE TITLE
Connection refused Error

### ISSUE THREAD

**Issue by Akimyou** [ThisIsQasim/TastyIgniter#6]
I run on docker-compose with error.

`In Connection.php line 712:
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `ti_users` where `username` = admin limit 1)
In Exception.php line 18:
  SQLSTATE[HY000] [2002] Connection refused
In PDOConnection.php line 40:
  SQLSTATE[HY000] [2002] Connection refused
`

**Comment by Akimyou** [comment]
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied

**Comment by nimeshgarg** [comment]
> I run on docker-compose with error.
> 
> `In Connection.php line 712: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `ti_users`where`username`= admin limit 1) In Exception.php line 18: SQLSTATE[HY000] [2002] Connection refused In PDOConnection.php line 40: SQLSTATE[HY000] [2002] Connection refused`

Facing same issue.
Any solution?

**Comment by ThisIsQasim** [comment]
The MySQL container takes a while to come up. Give it a few seconds before proceeding
